### ISSUE TITLE
Doesn't work on non-Windows

### ISSUE THREAD

**Issue by tommythorn** [xesscorp/XSTOOLs#1]
$ xstest.py 
Traceback (most recent call last):
  File "/usr/local/bin/xstest.py", line 5, in <module>
    pkg_resources.run_script('XsTools==0.1.0', 'xstest.py')
  File "/usr/lib/python2.7/site-packages/pkg_resources.py", line 499, in run_script
    self.require(requires)[0].run_script(script_name, ns)
  File "/usr/lib/python2.7/site-packages/pkg_resources.py", line 1239, in run_script
    execfile(script_filename, namespace, namespace)
  File "/usr/local/lib/python2.7/site-packages/XsTools-0.1.0-py2.7.egg/EGG-INFO/scripts/xstest.py", line 37, in <module>
    import winsound
ImportError: No module named winsound

"Win"sounds doesn't sound like it's a portable module.

Alas, even when this is corrected, other problems are hit.

**Comment by xesscorp** [comment]
On 1/23/2013 5:57 PM, Tommy Thorn wrote:

> $ xstest.py
> Traceback (most recent call last):
> File "/usr/local/bin/xstest.py", line 5, in
> pkg_resources.run_script('XsTools==0.1.0', 'xstest.py')
> File "/usr/lib/python2.7/site-packages/pkg_resources.py", line 499, in 
> run_script
> self.require(requires)[0].run_script(script_name, ns)
> File "/usr/lib/python2.7/site-packages/pkg_resources.py", line 1239, 
> in run_script
> execfile(script_filename, namespace, namespace)
> File 
> "/usr/local/lib/python2.7/site-packages/XsTools-0.1.0-py2.7.egg/EGG-INFO/scripts/xstest.py", 
> line 37, in
> import winsound
> ImportError: No module named winsound
> 
> "Win"sounds doesn't sound like it's a portable module.
> 
> Alas, even when this is corrected, other problems are hit.
> 
> —
> Reply to this email directly or view it on GitHub 
> https://github.com/xesscorp/XSTOOLs/issues/1.
> 
> Tommy, when you remove the need for the winsound package, are you 
> hitting the same problems you described in your previous emails or are 
> these different?

## 

---

Dave Vandenbout / XESS Corp.
2608 Sweetgum Drive
Apex NC 27539-8851
USA
/devb@xess.com/

## /www.xess.com/

**Comment by tommythorn** [comment]
The next problem I hit was

$ xstest.py
Traceback (most recent call last):
  File "/usr/local/bin/xstest.py", line 5, in <module>
    pkg_resources.run_script('XsTools==0.1.0', 'xstest.py')
  File "/usr/lib/python2.7/site-packages/pkg_resources.py", line 499, in run_script
    self.require(requires)[0].run_script(script_name, ns)
  File "/usr/lib/python2.7/site-packages/pkg_resources.py", line 1239, in run_script
    execfile(script_filename, namespace, namespace)
  File "/usr/local/lib/python2.7/site-packages/XsTools-0.1.0-py2.7.egg/EGG-INFO/scripts/xstest.py", line 38, in <module>
    import xstools.xsboard as XSBOARD
  File "/usr/local/lib/python2.7/site-packages/XsTools-0.1.0-py2.7.egg/xstools/xsboard.py", line 27, in <module>
    import wx
ImportError: No module named wx

**Comment by xesscorp** [comment]
On 1/23/2013 6:29 PM, Tommy Thorn wrote:

> The next problem I hit was
> 
> $ xstest.py
> Traceback (most recent call last):
> File "/usr/local/bin/xstest.py", line 5, in
> pkg_resources.run_script('XsTools==0.1.0', 'xstest.py')
> File "/usr/lib/python2.7/site-packages/pkg_resources.py", line 499, in 
> run_script
> self.require(requires)[0].run_script(script_name, ns)
> File "/usr/lib/python2.7/site-packages/pkg_resources.py", line 1239, 
> in run_script
> execfile(script_filename, namespace, namespace)
> File 
> "/usr/local/lib/python2.7/site-packages/XsTools-0.1.0-py2.7.egg/EGG-INFO/scripts/xstest.py", 
> line 38, in
> import xstools.xsboard as XSBOARD
> File 
> "/usr/local/lib/python2.7/site-packages/XsTools-0.1.0-py2.7.egg/xstools/xsboard.py", 
> line 27, in
> import wx
> ImportError: No module named wx
> 
> —
> Reply to this email directly or view it on GitHub 
> https://github.com/xesscorp/XSTOOLs/issues/1#issuecomment-12628873.

OK, thats wxpython. There isn't a way to automatically install that 
(that I could find), so you probably have to do it manually for the type 
of OS you are using. You can find the installers here: 
http://www.wxpython.org/download.php

## 

---

Dave Vandenbout / XESS Corp.
2608 Sweetgum Drive
Apex NC 27539-8851
USA
/devb@xess.com/

## /www.xess.com/

**Comment by tommythorn** [comment]
Why do I need wxpython for a command line utility? I'm using this remotely so there's no
window system anyway.

Installation of wxpython is non-trivial and more than I have time for now (there's no
existing package for openSUSE).

**Comment by xesscorp** [comment]
On 1/23/2013 6:49 PM, Tommy Thorn wrote:

> Why do I need wxpython for a command line utility? I'm using this 
> remotely so there's no
> window system anyway.
> 
> Installation of wxpython is non-trivial and more than I have time for 
> now (there's no
> existing package for openSUSE).
> 
> —
> Reply to this email directly or view it on GitHub 
> https://github.com/xesscorp/XSTOOLs/issues/1#issuecomment-12629566.
> 
> I'm using wxpython for the GUI portion of XSTOOLs. I also use the 
> publish/describe features in wxpython for handling some message passing 
> between components.

I'll see if I can produce an alternate version that removes wxpython for 
the command-line tools.

Thanks for your help with this. I do appreciate your feedback.

## 

---

Dave Vandenbout / XESS Corp.
2608 Sweetgum Drive
Apex NC 27539-8851
USA
/devb@xess.com/

## /www.xess.com/

**Comment by xesscorp** [comment]
On 1/23/2013 6:49 PM, Tommy Thorn wrote:

> Why do I need wxpython for a command line utility? I'm using this 
> remotely so there's no
> window system anyway.
> 
> Installation of wxpython is non-trivial and more than I have time for 
> now (there's no
> existing package for openSUSE).
> 
> —
> Reply to this email directly or view it on GitHub 
> https://github.com/xesscorp/XSTOOLs/issues/1#issuecomment-12629566.

I changed the package so it uses pypubsub instead of wxpython. Maybe 
that will work for you now.

pip install xstools

## 

---

Dave Vandenbout / XESS Corp.
2608 Sweetgum Drive
Apex NC 27539-8851
USA
/devb@xess.com/

## /www.xess.com/

**Comment by tommythorn** [comment]
Some good news at last:

I hadn't used pip before, but it was easy enough. However some DOSism must
have slipped in as xstest.py now complained

-bash: /usr/local/bin/xstest.py: /usr/bin/python^M: bad interpreter: No such file or directory

I don't know if this is the fault of pip, but I fixed that by hand and removed all winsound
references (again). After this xstest.py ran:

$ sudo xstest.py 
Success: XuLA-200 passed diagnostic test!

I had to apply the unDOS fix to xsload.py as well.

As far as I can tell at this point, it's working on openSUSE.

The only thing I need now is pc_blinker_test.py working with the python version of XSTOOLs (is that
already available somewhere?).

Thanks.

**Comment by xesscorp** [comment]
On 1/24/2013 12:40 AM, Tommy Thorn wrote:

> Some good news at last:
> 
> I hadn't used pip before, but it was easy enough. However some DOSism must
> have slipped in as xstest.py now complained
> 
> -bash: /usr/local/bin/xstest.py: /usr/bin/python^M: bad interpreter: 
> No such file or directory
> 
> I don't know if this is the fault of pip, but I fixed that by hand and 
> removed all winsound
> references (again). After this xstest.py ran:
> 
> $ sudo xstest.py
> Success: XuLA-200 passed diagnostic test!
> 
> I had to apply the unDOS fix to xsload.py as well.
> 
> As far as I can tell at this point, it's working on openSUSE.

While it is somewhat unprofessional, allow me to say "Whoopee".

> The only thing I need now is pc_blinker_test.py working with the 
> python version of XSTOOLs (is that
> already available somewhere?).
> 
> Thanks.
> 
> —
> Reply to this email directly or view it on GitHub 
> https://github.com/xesscorp/XSTOOLs/issues/1#issuecomment-12638266.

I'm working now on transferring the book chapters over to using the 
xstools package. I'll let you know later today when those are done.

## 

---

Dave Vandenbout / XESS Corp.
2608 Sweetgum Drive
Apex NC 27539-8851
USA
/devb@xess.com/

## /www.xess.com/
