### ISSUE TITLE
libusb exception messages on successful exit

### ISSUE THREAD

**Issue by bnewbold** [xesscorp/XSTOOLs#10]
After a successful upload with `xsload.py` ("Success: Bitstream XXX downloaded into XuLA2-LX25 !"), I get the following pyusb exceptions printed:

```
Exception AttributeError: "'NoneType' object has no attribute 'copy'" in <bound method Device.__del__ of <usb.core.Device object at 0x7f7a33ae64d0>> ignored
Exception AttributeError: "'NoneType' object has no attribute 'libusb_unref_device'" in <bound method _Device.__del__ of <usb.backend.libusb1._Device object at 0x7f7a33ae6490>> ignored
```

This is a known upstream problem with pyusb (see @xesscorp's comment https://github.com/xesscorp/XSTOOLs/issues/7#issuecomment-68215118 on a closed issue); i'm creating a separate issue to help other folks figure out what's going on.

**Comment by xesscorp** [comment]
This issue should have been fixed in XSTOOLs 0.1.29.
