### ISSUE TITLE
Raspberry Pi error - xstest.py with xula-200

### ISSUE THREAD

**Issue by gsun86** [xesscorp/XSTOOLs#6]
Installed xstools on RPI with its default Raspbian by:
  sudo apt-get install python-pip
  sudo pip install xstools

Already upgraded the firmware and test on PC with Enthought Python for xstest.py, successfully.

But got error with RPI on:
  sudo xstest.py
  ERROR: Failed to write required number of bytes over the USB link.
The LED on the xula-200 blinked for a while - almost working I guess.

Thanks.

Gang.

**Comment by tommythorn** [comment]
Does this reproduce the same way each time?

**Comment by gsun86** [comment]
Reproduced three times, with reboot RPI and unplug/plug-in xula-200.

**Comment by tommythorn** [comment]
Thanks. I suspect that we need to restart or resume the write.

Could you try applying this change and let us know that you get (this is not a fix!):

```
diff --git a/xstools/xsusb.py b/xstools/xsusb.py
index 41e6129..aa6da32 100644
--- a/xstools/xsusb.py
+++ b/xstools/xsusb.py
@@ -201,10 +201,9 @@ class XsUsb:

         logging.debug('OUT => (%d) %s', len(bytes), str([bin(x | 0x100)[3:] for x in bytes]))
         time_out = self._calc_time_out(len(bytes))
-        if self._dev.write(usb.util.ENDPOINT_OUT | self._endpoint,
-                           bytes, 0, time_out) \
-            != len(bytes):
-            raise XsMajorError('Failed to write required number of bytes over the USB link')
+        wrote = self._dev.write(usb.util.ENDPOINT_OUT | self._endpoint, bytes, 0, time_out)
+        if wrote != len(bytes):
+            raise XsMajorError('Failed to write % bytes over the USB link, wrote %d' % (len(bytes), wrote))

     def read(self, num_bytes=0):
         """Return a byte array read from an XESS board."""
```

**Comment by gsun86** [comment]
Copied into a script and run on RPI.  Came back with the following error:
     sudo /home/pi/FPGA/xess/tommythorn_12_15_2013.sh
     diff: unrecognized option '--git'

**Comment by tommythorn** [comment]
Huh? It's a diff, not a script. Just open xsusb.py in your editor, delete the lines prefixed with - above and replace them with the lines prefixed with + (and obviously remove the +).

**Comment by gsun86** [comment]
Thanks for the instruction.  I did the above change in xsusb.py.  Somehow the error is on USB read now.  The board has the initial busrt of blinks (3 or 4 time).  Outputs here:
Traceback (most recent call last):
  File "/usr/local/bin/xstest.py", line 66, in <module>
    xs_board = XSBOARD.XsBoard.get_xsboard(args.usb)
  File "/usr/local/lib/python2.7/dist-packages/xstools/xsboard.py", line 56, in get_xsboard
    if xsboard.is_connected():
  File "/usr/local/lib/python2.7/dist-packages/xstools/xsboard.py", line 98, in is_connected
    return self.fpga.is_connected()
  File "/usr/local/lib/python2.7/dist-packages/xstools/xilfpga.py", line 76, in is_connected
    return self.get_idcode().head(28) == self._IDCODE.head(28)
  File "/usr/local/lib/python2.7/dist-packages/xstools/xilfpga.py", line 71, in get_idcode
    return self.xsjtag.load_ir_then_dr(instruction=self._IDCODE_INSTR, data=None, num_return_bits=IDCODE_LENGTH)
  File "/usr/local/lib/python2.7/dist-packages/xstools/xsjtag.py", line 285, in load_ir_then_dr
    bits = self.shift_tdo(num_bits=num_return_bits, do_exit_shift=True)
  File "/usr/local/lib/python2.7/dist-packages/xstools/xsjtag.py", line 126, in shift_tdo
    tdo_bits = self.shift_tdo(num_bits=num_bits - 0x01, do_exit_shift=False)
  File "/usr/local/lib/python2.7/dist-packages/xstools/xsjtag.py", line 143, in shift_tdo
    buffer = self._xsusb.read(num_bytes)
  File "/usr/local/lib/python2.7/dist-packages/xstools/xsusb.py", line 217, in read
    num_bytes, 0, time_out)
  File "/usr/local/lib/python2.7/dist-packages/usb/core.py", line 670, in read
    self.__get_timeout(timeout)
  File "/usr/local/lib/python2.7/dist-packages/usb/backend/libusb1.py", line 780, in bulk_read
    timeout)
  File "/usr/local/lib/python2.7/dist-packages/usb/backend/libusb1.py", line 889, in __read
    _check(retval)
  File "/usr/local/lib/python2.7/dist-packages/usb/backend/libusb1.py", line 571, in _check
    raise USBError(_str_error[ret], ret, _libusb_errno[ret])
usb.core.USBError: [Errno 110] Operation timed out

**Comment by tommythorn** [comment]
Oh hang on, Raspberry Pi? Did you plug the XuLA directly into the Pi? Please be sure to use an externally _powered_ USB hub. The Raspberry Pi has some well-known issues with USB power delivery. I have reworked mine to improve this. This is very likely to be the issue.

**Comment by gsun86** [comment]
Yes you were right!  With an external 5V power supply it was Success: XuLA-200 passed diagnostic test! 
Thanks a lot for the help.  - Gang

**Comment by xesscorp** [comment]
Hi, Tommy. Thanks for solving their problem!

> Oh hang on, Raspberry Pi? Did you plug the XuLA directly into the Pi? 
> Please be sure to use an externally /powered/ USB hub. The Raspberry 
> Pi has some well-known issues with USB power delivery. I have reworked 
> mine to improve this. This is very likely to be the issue.
> 
> —
> Reply to this email directly or view it on GitHub 
> https://github.com/xesscorp/XSTOOLs/issues/6#issuecomment-30690682.

## 

---

Dave Vandenbout / XESS Corp.
2608 Sweetgum Drive
Apex NC 27539-8851
USA
/devb@xess.com/

## /www.xess.com/
