### ISSUE TITLE
Issues on Unix (Linux & Mac OS X)

### ISSUE THREAD

**Issue by tommythorn** [xesscorp/XSTOOLs#7]
cloned and installed.  Doesn't work out the box on Linux because of DOS line endings and Windows assumptions.

```
$ gxstools.py 
bash: /usr/bin/gxstools.py: C:\WinPython\Python-2.7.5\python.exe^M: bad interpreter: No such file or directory
```

**Comment by xesscorp** [comment]
On 03/09/2014 3:45 AM, Tommy Thorn wrote:

> cloned and installed. Doesn't work out the box because of DOS line 
> endings:
> 
> |    $ gxstools.py
> bash: /usr/bin/gxstools.py: C:\WinPython\Python-2.7.5\python.exe^M: bad interpreter: No such file or directory
> |
> 
> —
> Reply to this email directly or view it on GitHub 
> https://github.com/xesscorp/XSTOOLs/issues/7.

Thanks, Tommy.

## 

---

Dave Vandenbout / XESS Corp.
2608 Sweetgum Drive
Apex NC 27539-8851
USA
/devb@xess.com/

## /www.xess.com/

**Comment by xesscorp** [comment]
On 03/09/2014 3:45 AM, Tommy Thorn wrote:

> cloned and installed. Doesn't work out the box because of DOS line 
> endings:
> 
> |    $ gxstools.py
> bash: /usr/bin/gxstools.py: C:\WinPython\Python-2.7.5\python.exe^M: bad interpreter: No such file or directory
> |
> 
> —
> Reply to this email directly or view it on GitHub 
> https://github.com/xesscorp/XSTOOLs/issues/7.
> 
> Hi, Tommy. I checked this and the line ending settings are correct. The 
> problem was the first line in gxstools.py was pointing to the WinPython 
> interpreter I use on Windows. I changed it to "/usr/bin/python" like the 
> others. Hopefully it will work now.

## 

---

Dave Vandenbout / XESS Corp.
2608 Sweetgum Drive
Apex NC 27539-8851
USA
/devb@xess.com/

## /www.xess.com/

**Comment by tommythorn** [comment]
Thanks. FWIW, doing a `sudo pip install xstools` ignores my local files and downloads xstools from somewhere. I found that using `sudo python setup.py install` worked.

Next problem was a dependency on `wx` to which I replied `sudo pip install wx`. Alas, I haven't been able to get past the latest issue:

```
Traceback (most recent call last):
  File "/usr/bin/gxstools.py", line 5, in <module>
    pkg_resources.run_script('XsTools==0.1.12', 'gxstools.py')
  File "/usr/lib/python2.7/site-packages/pkg_resources.py", line 540, in run_script
    self.require(requires)[0].run_script(script_name, ns)
  File "/usr/lib/python2.7/site-packages/pkg_resources.py", line 1455, in run_script
    execfile(script_filename, namespace, namespace)
  File "/usr/lib/python2.7/site-packages/XsTools-0.1.12-py2.7.egg/EGG-INFO/scripts/gxstools.py", line 35, in <module>
    import wx.lib
ImportError: No module named lib
```

**Comment by tommythorn** [comment]
It appears that the original problem disappeared, but I'm facing a different one:

```
$ xstest.py
Traceback (most recent call last):
  File "/usr/bin/xstest.py", line 73, in <module>
    num_boards = XSBOARD.XsUsb.get_num_xsusb()
  File "/usr/lib/python2.7/site-packages/xstools/xsusb.py", line 170, in get_num_xsusb
    return len(cls.get_xsusb_ports())
  File "/usr/lib/python2.7/site-packages/xstools/xsusb.py", line 155, in get_xsusb_ports
    for i in range(len(devs)):
TypeError: object of type 'generator' has no len()
```

My best guess is that XSTOOLs expects a different behaviour from the usb.core package that it's getting.
FWIW, this is on openSUSE 20140918.

**Comment by xesscorp** [comment]
On 11/20/2014 1:35 AM, Tommy Thorn wrote:

> It appears that the original problem disappeared, but I'm facing a 
> different one:
> 
> |$ xstest.py
> Traceback (most recent call last):
>    File "/usr/bin/xstest.py", line 73, in <module>
>      num_boards = XSBOARD.XsUsb.get_num_xsusb()
>    File "/usr/lib/python2.7/site-packages/xstools/xsusb.py", line 170, in get_num_xsusb
>      return len(cls.get_xsusb_ports())
>    File "/usr/lib/python2.7/site-packages/xstools/xsusb.py", line 155, in get_xsusb_ports
>      for i in range(len(devs)):
> TypeError: object of type 'generator' has no len()
> |
> 
> My best guess is that XSTOOLs expect a different behaviour from the 
> usr.core package that it's getting.
> FWIW, this is on openSUSE 20140918.
> 
> —
> Reply to this email directly or view it on GitHub 
> https://github.com/xesscorp/XSTOOLs/issues/7#issuecomment-63767092.
> 
> Hi, Tommy. Got to 
> https://github.com/xesscorp/XSTOOLs/tree/tommy/xstools, get the xsusb.py 
> file and use it in place of the one you have. I made a change to remove 
> the generator error. I don't know if it will fix your problem, but at 
> least it doesn't break anything at my place.

Let me know if this fixes your problem so I can roll it into the next 
release.

## 

---

Dave Vandenbout / XESS Corp.
2608 Sweetgum Drive
Apex NC 27539-8851
USA
/devb@xess.com/

## /www.xess.com/

**Comment by tommythorn** [comment]
Thanks, that solves that problem.  I unfortunately get a "ERROR: No XESS Boards found!",
but I'm sure that's something else and I'll close this issue. Thanks!

**Comment by tommythorn** [comment]
I'm sorry, but I spoke too soon.  AFAICT, this is very much the issue.  I debugged this for about an hour, but I couldn't get it to work. It does find the XuLA2, but the first write to the USB device throws an exception (can't tell which).  I'll try to find more time later.

**Comment by xesscorp** [comment]
Thanks, Tommy. Keep me updated. Send me any exception dumps like last time.

Also, at the end of usb/core.py there is a loop like this that 
instantiates the backend USB library that gets used:

```
 if backend is None:
     import usb.backend.libusb1 as libusb1
     import usb.backend.libusb0 as libusb0
     import usb.backend.openusb as openusb

     for m in (libusb1, openusb, libusb0):
         backend = m.get_backend()
         if backend is not None:
             _logger.info('find(): using backend "%s"', m.__name__)
             break
     else:
         raise ValueError('No backend available')
```

I'm not sure what backend you're using, but you might try installing 
another one (libusb0, libusb1, or openusb) and then change the library 
order in the loop. Maybe using another library will shed some light on 
the problem.

> I'm sorry, but I spoke too soon. AFAICT, this is very much the issue. 
> I debugged this for about an hour, but I couldn't get it to work. It 
> does find the XuLA2, but the first write to the USB device throws an 
> exception (can't tell which). I'll try to find more time later.
> 
> —
> Reply to this email directly or view it on GitHub 
> https://github.com/xesscorp/XSTOOLs/issues/7#issuecomment-63935310.

## 

---

Dave Vandenbout / XESS Corp.
2608 Sweetgum Drive
Apex NC 27539-8851
USA
/devb@xess.com/

## /www.xess.com/

**Comment by tommythorn** [comment]
I just tried on Mac OS X and it behaves the same way as on Linux.

FWIW, I installed with

```
$ brew install python
$ pip install xstools --allow-all-external --allow-unverified intelhex
$ sudo xstest.py
Password:
Traceback (most recent call last):
  File "/usr/local/bin/xstest.py", line 73, in <module>
    num_boards = XSBOARD.XsUsb.get_num_xsusb()
  File "/usr/local/lib/python2.7/site-packages/xstools/xsusb.py", line 170, in get_num_xsusb
    return len(cls.get_xsusb_ports())
  File "/usr/local/lib/python2.7/site-packages/xstools/xsusb.py", line 149, in get_xsusb_ports
    idProduct=cls._PRODUCT_ID, find_all=True))
  File "/usr/local/lib/python2.7/site-packages/usb/core.py", line 864, in find
    raise ValueError('No backend available')
ValueError: No backend available
```

**Comment by tommythorn** [comment]
I tried something and got a different error:

```
$ brew install libusb
$ sudo xstest.py
Password:
Traceback (most recent call last):
  File "/usr/local/bin/xstest.py", line 78, in <module>
    xs_board.do_self_test()
AttributeError: XulaOldFmw instance has no attribute 'do_self_test'
Exception AttributeError: "'NoneType' object has no attribute 'copy'" in <bound method Device.__del__ of <usb.core.Device object at 0x10c62ef50>> ignored
Exception AttributeError: "'NoneType' object has no attribute 'libusb_unref_device'" in <bound method _Device.__del__ of <usb.backend.libusb1._Device object at 0x10c62ef10>> ignored
```

**Comment by tommythorn** [comment]
I don't do much with Python so I didn't realize that pip install xstools didn't install the local version, but instead downloaded an older release (XsTools-0.1.20).

Tried something different again and a slightly different behaviour:

```
$ easy_install XSTOOLs
$ sudo xstest.py
Please disconnect your XESS board ... thanks!
Please reconnect your XESS board ... thanks!
Traceback (most recent call last):
  File "/usr/local/bin/xstest.py", line 4, in <module>
    __import__('pkg_resources').run_script('XsTools==0.1.19', 'xstest.py')
  File "build/bdist.macosx-10.10-x86_64/egg/pkg_resources.py", line 534, in run_script
  File "build/bdist.macosx-10.10-x86_64/egg/pkg_resources.py", line 1438, in run_script
  File "/usr/local/lib/python2.7/site-packages/XsTools-0.1.19-py2.7.egg/EGG-INFO/scripts/xstest.py", line 78, in <module>
    xs_board.do_self_test()
AttributeError: XulaOldFmw instance has no attribute 'do_self_test'
Exception AttributeError: "'NoneType' object has no attribute 'copy'" in <bound method Device.__del__ of <usb.core.Device object at 0x10e265a90>> ignored
Exception AttributeError: "'NoneType' object has no attribute 'libusb_unref_device'" in <bound method _Device.__del__ of <usb.backend.libusb1._Device object at 0x10e265a50>> ignored
Exception AttributeError: "'NoneType' object has no attribute 'copy'" in <bound method Device.__del__ of <usb.core.Device object at 0x10e265d50>> ignored
Exception AttributeError: "'NoneType' object has no attribute 'libusb_unref_device'" in <bound method _Device.__del__ of <usb.backend.libusb1._Device object at 0x10e265ed0>> ignored
```

**Comment by tommythorn** [comment]
Ough. Seeing references to "XulaOldFmw" made me wonder if the firmware was out of date, so I loaded up the Windows distribution of XSTOOLs in a Windows VM, verified that gxstest passed and then hit the "Update XuLA2 Firmware" entry.  That seems to fail (consistently). A shell window pops up and with the contents (transcribed from screenshot)

```

C:\Program Files (x86)\XSTOOLs\XuLA2\Firmware\xsusbprg -usb 0 -f XuLA_jtag.hex
 MINOR ERROR: MPUSBWrite() failed: A device attached to the system is not functi
oning.
MPUSBWrite() failed: A device attached to the system is not functioning.
 MAJOR ERROR: Error while resetting board!
Error while resetting board!

Flash Erase:
Erasing flash: 96%
```

It probably hit 100% as the window disappears. However, now gxstest hangs (rebooting, replugging, re-updating, etc, to no avail).  Bricked board it would seem.

**Comment by tommythorn** [comment]
I apologize for the verbosity of the reports, but it does present the reality of my XuLA2 experience.  I tried updating from the git python sources.  That seemed to work better, but xstest.py still isn't totally happy:

```
$ xsusbprg.py -f XSTOOLs/xstools/xula2/XuLA_jtag.hex
Programming microcontroller firmware with XuLA_jtag.hex.
Please disconnect your XESS board ... thanks!
Please reconnect your XESS board ... thanks!
Please disconnect your XESS board ... thanks!
Please reconnect your XESS board ... thanks!
Programming completed!
$ xstest.py 
Success: XuLA2-LX25 passed diagnostic test!
Exception AttributeError: "'NoneType' object has no attribute 'copy'" in <bound method Device.__del__ of <usb.core.Device object at 0x110989b50>> ignored
Exception AttributeError: "'NoneType' object has no attribute 'libusb_unref_device'" in <bound method _Device.__del__ of <usb.backend.libusb1._Device object at 0x110989b10>> ignored
```

However, now gxstest in the VM is happy again.

**Comment by xesscorp** [comment]
Hi, Tommy. I think installing the latest version of the python xstools 
(0.1.20) and flashing the latest firmware into the XuLA board has cured 
most of your problems.

The two exceptions you're seeing are caused by the pyusb library. They 
get thrown as the program terminates. They don't affect the actual 
functions of the program. One of the pyusb developers says they may have 
a fix. I'll have to try it or else catch-and-ignore those exceptions 
upon program exit.

Thanks for the details on the program exceptions and outputs. It helps 
to determine what's going on. Let me know if you see any further 
anomalous behavior.

> I apologize for the verbosity of the reports, but it does present the 
> reality of my XuLA2 experience. I tried updating from the git python 
> sources. That seemed to work better, but xstest.py still isn't totally 
> happy:
> 
> |$ xsusbprg.py -f XSTOOLs/xstools/xula2/XuLA_jtag.hex
> Programming microcontroller firmware with XuLA_jtag.hex.
> Please disconnect your XESS board ... thanks!
> Please reconnect your XESS board ... thanks!
> Please disconnect your XESS board ... thanks!
> Please reconnect your XESS board ... thanks!
> Programming completed!
> $ xstest.py
> Success: XuLA2-LX25 passed diagnostic test!
> Exception AttributeError: "'NoneType' object has no attribute 'copy'" in <bound method Device.__del__ of <usb.core.Device object at 0x110989b50>> ignored
> Exception AttributeError: "'NoneType' object has no attribute 'libusb_unref_device'" in <bound method _Device.__del__ of <usb.backend.libusb1._Device object at 0x110989b10>> ignored
> |
> 
> However, now gxstest in the VM is happy again.
> 
> —
> Reply to this email directly or view it on GitHub 
> https://github.com/xesscorp/XSTOOLs/issues/7#issuecomment-68200526.

## 

---

Dave Vandenbout / XESS Corp.
2608 Sweetgum Drive
Apex NC 27539-8851
USA
/devb@xess.com/

## /www.xess.com/

**Comment by tommythorn** [comment]
Ok, I have success with one example on MacOS X, so I'll ignore Linux problems.
