### ISSUE TITLE
Travis CI account broken (repo renamed?)

### ISSUE THREAD

**Issue by bnewbold** [xesscorp/XSTOOLs#9]
This repository points to "https://travis-ci.org/xesscorp/XsTools"; it should probably be "https://travis-ci.org/xesscorp/XSTOOLs"? Though an Travis page doesn't exist at either location.

**Comment by xesscorp** [comment]
The Travis account is an artifact of the cookiecutter template I used for this project. I'll either:
- Figure out how to use Travis, or
- Remove the Travis-related stuff.

**Comment by bnewbold** [comment]
Removed a long time ago, closing.

Thanks so much for releasing XSTOOLs!
